---
unattended_upgrades_enabled: True
unattended_upgrades_generic: False

unattended_upgrades_packages:
  - 'unattended-upgrades'

unattended_upgrades_security_origins:
  - '"${distro_id}:${distro_codename}";'
  - '"${distro_id}:${distro_codename}-security";'
  - '"${distro_id}ESM:${distro_codename}";'

unattended_upgrades_generic_origins:
  - '"${distro_id}:${distro_codename}-updates";'
  - '"${distro_id}:${distro_codename}-proposed";'
  - '"${distro_id}:${distro_codename}-backports";'

unattended_upgrades_autofixinterrupteddpkg: True
unattended_upgrades_minimalsteps: True
unattended_upgrades_mailfrom: '{{ system_mailfrom | d() }}'
unattended_upgrades_mailto: '{{ system_mailto }}'
unattended_upgrades_mailonlyonerror: True
unattended_upgrades_removeunusedkernel: True
unattended_upgrades_removeunused: False
unattended_upgrades_autoreboot: False
unattended_upgrades_autoreboottime: '{{ "02:30" if (ansible_virtualization_role in [ "host", "NA" ])
                                        else "02:42"
                                    }}'
