---

timesyncd_enabled: "{{ 'False' if (ansible_facts.virtualization_type in [ 'lxc' ])
                              else 'True' }}"

timedatectl_servers:
  - "0.debian.pool.ntp.org"
  - "1.debian.pool.ntp.org"

timedatectl_servers_fallback:
  - "2.debian.pool.ntp.org"
  - "3.debian.pool.ntp.org"

timedatectl_timezone: "Etc/UTC"
