galaxy_info:
  author: SmartOps.Academy
  description: Configures network interfaces on Debian and Ubuntu.
  company: SmartOps Academy

  license: CC-BY-SA

  min_ansible_version: 2.4

  github_branch: https://github.com/SmartOpsAcademy/ansible/roles/network_configuration

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - debian
    - ubuntu
    - network
    - dns
    - networkconfiguration

dependencies: []
